
//
// @@tarat generated file
// provide by @tarat
// warning: auto generated by tarat.do not modifed this file
//
import d from 'tarat-user-login-system/dist/drivers/login'
Object.assign(d, { __tarat_compose__: true })
export { default } from 'tarat-user-login-system/dist/drivers/login'
