
//
// @@tarat generated file
// provide by @tarat
// warning: auto generated by tarat.do not modifed this file
//
import d from 'tarat-markdown-editor/dist/drivers/mdList'
Object.assign(d, { __tarat_compose__: true })
export { default } from 'tarat-markdown-editor/dist/drivers/mdList'
